spring:
  application:
    name: java25-flink

  server:
    port: 8081

  flink:
    jobmanager:
      host: localhost
      port: 6123
    rest:
      url: http://localhost:8082
    jar:
      path: target/java25-flink-0.0.1-SNAPSHOT.jar

  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics