spring:
  application:
    name: java25-flink

server:
  port: 8080

flink:
  jobmanager:
    host: localhost
    port: 6123
  rest:
    url: http://localhost:8081
  jar:
    path: target/java25-flink-1.0-SNAPSHOT.jar

kafka:
  bootstrap-servers: localhost:9092
  input-topic: words-input
  output-topic: words-output
  group-id: flink-word-count
  transactions-topic: transactions-input
  fraud-alerts-topic: fraud-alerts
  user-events-topic: user-events
  session-summaries-topic: session-summaries

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
